server:
  port: 8080
  servlet:
    context-path: /pizzeria

spring:
  datasource:
    username: postgres
    password: BuSI
    url: jdbc:postgresql://localhost:5432/pizzeriatestdb
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true